import 'package:dart_monty_ide/src/ui/python_chunk_analyzer.dart';
import 'package:flutter/material.dart';
import 'package:re_editor/re_editor.dart';
import 'package:re_highlight/styles/atom-one-dark.dart';

/// A buffer that displays and allows editing code generated by the AI Assistant.
class MontyAssistantBuffer extends StatefulWidget {
  /// Creates a [MontyAssistantBuffer].
  const MontyAssistantBuffer({
    required this.controller,
    required this.onPrompt,
    required this.onRun,
    required this.onTypeCheck,
    required this.onSaveAs,
    this.isProcessing = false,
    super.key,
  });

  /// The controller for the code editor.
  final CodeLineEditingController controller;

  /// Callback when a new prompt is submitted.
  final ValueChanged<String> onPrompt;

  /// Callback when the run button is pressed.
  final ValueChanged<String> onRun;

  /// Callback when the type check button is pressed.
  final ValueChanged<String> onTypeCheck;

  /// Callback when the save as button is pressed.
  final ValueChanged<String> onSaveAs;

  /// Whether the assistant is currently processing.
  final bool isProcessing;

  @override
  State<MontyAssistantBuffer> createState() => _MontyAssistantBufferState();
}

class _MontyAssistantBufferState extends State<MontyAssistantBuffer> {
  final TextEditingController _promptController = TextEditingController();

  @override
  void dispose() {
    _promptController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Expanded(
          child: CodeEditor(
            controller: widget.controller,
            chunkAnalyzer: const DefaultCodeChunkAnalyzer(),
            readOnly: false, // Allow guiding/tweaking
            wordWrap: false,
            style: CodeEditorStyle(
              fontSize: 13,
              codeTheme: CodeHighlightTheme(
                languages: {},
                theme: atomOneDarkTheme,
              ),
            ),
            indicatorBuilder:
                (context, editingController, chunkController, notifier) {
              return Row(
                children: [
                  DefaultCodeLineNumber(
                    controller: editingController,
                    notifier: notifier,
                  ),
                  DefaultCodeChunkIndicator(
                    width: 20,
                    controller: chunkController,
                    notifier: notifier,
                  ),
                ],
              );
            },
          ),
        ),
        Container(
          padding: const EdgeInsets.all(8),
          decoration: BoxDecoration(
            color: Theme.of(context).cardColor,
            border:
                Border(top: BorderSide(color: Theme.of(context).dividerColor)),
          ),
          child: Row(
            children: [
              Expanded(
                child: TextField(
                  controller: _promptController,
                  decoration: const InputDecoration(
                    hintText: 'Command the AI Pilot (e.g. "Build DFS")...',
                    border: OutlineInputBorder(),
                    isDense: true,
                    contentPadding:
                        EdgeInsets.symmetric(horizontal: 12, vertical: 8),
                  ),
                  onSubmitted: (val) {
                    if (val.isNotEmpty && !widget.isProcessing) {
                      widget.onPrompt(val);
                      _promptController.clear();
                    }
                  },
                ),
              ),
              const SizedBox(width: 8),
              IconButton(
                onPressed: () => widget.onSaveAs(widget.controller.text),
                icon: const Icon(Icons.save_alt, color: Colors.blueGrey),
                tooltip: 'Save As File',
              ),
              IconButton(
                onPressed: () => widget.onTypeCheck(widget.controller.text),
                icon: const Icon(Icons.fact_check_outlined, color: Colors.blue),
                tooltip: 'Type Check AI Buffer',
              ),
              IconButton(
                onPressed: () => widget.onRun(widget.controller.text),
                icon: const Icon(Icons.play_arrow, color: Colors.green),
                tooltip: 'Run AI Buffer',
              ),
              IconButton(
                onPressed: widget.isProcessing
                    ? null
                    : () {
                        final val = _promptController.text;
                        if (val.isNotEmpty) {
                          widget.onPrompt(val);
                          _promptController.clear();
                        }
                      },
                icon: widget.isProcessing
                    ? const SizedBox(
                        width: 20,
                        height: 20,
                        child: CircularProgressIndicator(strokeWidth: 2),
                      )
                    : const Icon(Icons.bolt, color: Colors.purple),
                tooltip: 'Trigger AI Pilot',
              ),
            ],
          ),
        ),
      ],
    );
  }
}
