import 'package:flutter/material.dart';
import 'package:re_editor/re_editor.dart';
import 'package:re_highlight/languages/python.dart';
import 'package:re_highlight/styles/atom-one-dark.dart';

/// A buffer that displays and allows editing code generated by the AI
/// Assistant.
class MontyAssistantBuffer extends StatefulWidget {
  /// Creates a [MontyAssistantBuffer].
  const MontyAssistantBuffer({
    required this.controller,
    required this.onPrompt,
    required this.onRun,
    required this.onTypeCheck,
    required this.onSaveAs,
    this.isProcessing = false,
    super.key,
  });

  /// The controller for the code editor.
  final CodeLineEditingController controller;

  /// Callback when a new prompt is submitted.
  final ValueChanged<String> onPrompt;

  /// Callback when the run button is pressed.
  final ValueChanged<String> onRun;

  /// Callback when the type check button is pressed.
  final ValueChanged<String> onTypeCheck;

  /// Callback when the save as button is pressed.
  final ValueChanged<String> onSaveAs;

  /// Whether the assistant is currently processing.
  final bool isProcessing;

  @override
  State<MontyAssistantBuffer> createState() => _MontyAssistantBufferState();
}

class _MontyAssistantBufferState extends State<MontyAssistantBuffer> {
  final FocusNode _focusNode = FocusNode();

  @override
  void dispose() {
    _focusNode.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        if (widget.isProcessing) const LinearProgressIndicator(minHeight: 2),
        Expanded(
          child: CodeEditor(
            controller: widget.controller,
            focusNode: _focusNode,
            chunkAnalyzer: const DefaultCodeChunkAnalyzer(),
            readOnly: false, // Allow guiding/tweaking
            wordWrap: false,
            autofocus: true,
            style: CodeEditorStyle(
              fontSize: 13,
              codeTheme: CodeHighlightTheme(
                languages: {
                  'python': CodeHighlightThemeMode(mode: langPython),
                },
                theme: atomOneDarkTheme,
              ),
            ),
            indicatorBuilder:
                (context, editingController, chunkController, notifier) {
                  return Row(
                    children: [
                      DefaultCodeLineNumber(
                        controller: editingController,
                        notifier: notifier,
                      ),
                      DefaultCodeChunkIndicator(
                        width: 20,
                        controller: chunkController,
                        notifier: notifier,
                      ),
                    ],
                  );
                },
          ),
        ),
      ],
    );
  }
}
