import 'package:flutter/material.dart';
import 'package:re_editor/re_editor.dart';
import 'package:re_highlight/styles/atom-one-dark.dart';

/// A read-only buffer that displays code generated by the AI Assistant.
class MontyAssistantBuffer extends StatefulWidget {
  /// Creates a [MontyAssistantBuffer].
  const MontyAssistantBuffer({
    required this.codeStream,
    required this.onPrompt,
    this.isProcessing = false,
    super.key,
  });

  /// The stream of code chunks to display.
  final Stream<String> codeStream;

  /// Callback when a new prompt is submitted.
  final ValueChanged<String> onPrompt;

  /// Whether the assistant is currently processing.
  final bool isProcessing;

  @override
  State<MontyAssistantBuffer> createState() => _MontyAssistantBufferState();
}

class _MontyAssistantBufferState extends State<MontyAssistantBuffer> {
  final CodeLineEditingController _controller = CodeLineEditingController();
  final TextEditingController _promptController = TextEditingController();

  @override
  void initState() {
    super.initState();
    widget.codeStream.listen((code) {
      if (mounted) {
        _controller.text = code;
      }
    });
  }

  @override
  void dispose() {
    _controller.dispose();
    _promptController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Expanded(
          child: CodeEditor(
            controller: _controller,
            readOnly: true,
            wordWrap: false,
            style: CodeEditorStyle(
              fontSize: 13,
              codeTheme: CodeHighlightTheme(
                languages: {},
                theme: atomOneDarkTheme,
              ),
            ),
          ),
        ),
        Container(
          padding: const EdgeInsets.all(8),
          decoration: BoxDecoration(
            color: Theme.of(context).cardColor,
            border:
                Border(top: BorderSide(color: Theme.of(context).dividerColor)),
          ),
          child: Row(
            children: [
              Expanded(
                child: TextField(
                  controller: _promptController,
                  decoration: const InputDecoration(
                    hintText: 'Command the AI Pilot (e.g. "Build DFS")...',
                    border: OutlineInputBorder(),
                    isDense: true,
                    contentPadding:
                        EdgeInsets.symmetric(horizontal: 12, vertical: 8),
                  ),
                  onSubmitted: (val) {
                    if (val.isNotEmpty && !widget.isProcessing) {
                      widget.onPrompt(val);
                      _promptController.clear();
                    }
                  },
                ),
              ),
              const SizedBox(width: 8),
              IconButton(
                onPressed: widget.isProcessing
                    ? null
                    : () {
                        final val = _promptController.text;
                        if (val.isNotEmpty) {
                          widget.onPrompt(val);
                          _promptController.clear();
                        }
                      },
                icon: widget.isProcessing
                    ? const SizedBox(
                        width: 20,
                        height: 20,
                        child: CircularProgressIndicator(strokeWidth: 2),
                      )
                    : const Icon(Icons.bolt, color: Colors.purple),
                tooltip: 'Trigger AI Pilot',
              ),
            ],
          ),
        ),
      ],
    );
  }
}
